class Mass:
    Tonnes = "Tonnes"
    Kilogram = "Kilogram"
    Gram = "Gram"
    Milligram = "Milligram"
    Microgram = "Microgram"
    ImperialTon = "ImperialTon"
    UsTon = "UsTon"
    Stone = "Stone"
    Pound = "Pound"
    Ounce = "Ounce"